version: '3'

services:
  start:
    build:
      context: .
      dockerfile: Dockerfile_start
    restart: always


  process:
    build:
      context: .
      dockerfile: Dockerfile_process
    restart: always

