version: '3'

services:
  script1:
    build:
      context: .
      dockerfile: Dockerfile_start
    restart: always


  script2:
    build:
      context: .
      dockerfile: Dockerfile_process
    restart: always

